title: Optivem Framework (.NET Core 2.2)
description: Enterprise Software Framework for .NET Core 2.2 Applications
google_analytics: UA-63306472-4
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions